const Teams = [
    {
        "position": 1,
        "image": "url",
        "name": "Arsenal",
        "played": 31,
        "won": 22,
        "drawn": 5,
        "lost": 4,
        "gf": 75,
        "ga": 24,
        "gd": 51,
        "points": 71
    },
    {
        "position": 2,
        "image": "url",
        "name": "Liverpool",
        "played": 31,
        "won": 21,
        "drawn": 8,
        "lost": 2,
        "gf": 72,
        "ga": 30,
        "gd": 42,
        "points": 71
    },
    {
        "position": 3,
        "image": "url",
        "name": "Manchester City",
        "played": 31,
        "won": 21,
        "drawn": 7,
        "lost": 3,
        "gf": 71,
        "ga": 31,
        "gd": 40,
        "points": 70
    },
    {
        "position": 4,
        "image": "url",
        "name": "Tottenham Hotspur",
        "played": 31,
        "won": 18,
        "drawn": 6,
        "lost": 7,
        "gf": 65,
        "ga": 45,
        "gd": 20,
        "points": 60
    },
    {
        "position": 5,
        "image": "url",
        "name": "Aston Villa",
        "played": 32,
        "won": 18,
        "drawn": 6,
        "lost": 8,
        "gf": 66,
        "ga": 49,
        "gd": 17,
        "points": 60
    },
    {
        "position": 6,
        "image": "url",
        "name": "Manchester United",
        "played": 31,
        "won": 15,
        "drawn": 4,
        "lost": 12,
        "gf": 55,
        "ga": 46,
        "gd": -1,
        "points": 49
    },
    {
        "position": 7,
        "image": "url",
        "name": "West Ham United",
        "played": 32,
        "won": 13,
        "drawn": 9,
        "lost": 10,
        "gf": 52,
        "ga": 56,
        "gd": -4,
        "points": 48
    },
    {
        "position": 8,
        "image": "url",
        "name": "Newcastle United",
        "played": 31,
        "won": 14,
        "drawn": 5,
        "lost": 12,
        "gf": 65,
        "ga": 52,
        "gd": 13,
        "points": 47
    },
    {
        "position": 9,
        "image": "url",
        "name": "Chelsea",
        "played": 30,
        "won": 12,
        "drawn": 8,
        "lost": 10,
        "gf": 55,
        "ga": 52,
        "gd": 3,
        "points": 44
    },
    {
        "position": 10,
        "image": "url",
        "name": "Brighton And Hove Albion",
        "played": 31,
        "won": 11,
        "drawn": 10,
        "lost": 10,
        "gf": 51,
        "ga": 49,
        "gd": 2,
        "points": 43
    }
]

export default Teams;